# Generated by Django 4.1.1 on 2022-09-28 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_organizador', models.CharField(max_length=30)),
                ('correo_organizador', models.CharField(max_length=30)),
                ('telefono_organizador', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['nombre_organizador'],
            },
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_torneo', models.CharField(max_length=30)),
                ('fecha_torneo_inicio', models.DateField(null=True)),
                ('fecha_torneo_fin', models.DateField(null=True)),
                ('pais_torneo', models.CharField(max_length=30)),
                ('torneo_estado', models.BooleanField(default=True)),
                ('invitacion_documento', models.FileField(upload_to='')),
                ('id_organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.organizador')),
            ],
        ),
        migrations.CreateModel(
            name='Etapa_Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_inscripcion', models.CharField(max_length=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('monto_inscripcion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.torneo')),
            ],
        ),
        migrations.CreateModel(
            name='Categorias_Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=30)),
                ('edad_minima', models.IntegerField()),
                ('edad_maxima', models.IntegerField()),
                ('id_torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.torneo')),
            ],
        ),
    ]
