# Generated by Django 4.1 on 2022-10-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0003_alter_torneo_invitacion_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='logo',
            field=models.ImageField(null=True, upload_to='static/imagenes/logos/', verbose_name='LogoTorneo'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='invitacion_documento',
            field=models.FileField(upload_to='static/imagenes/convocatorias/', verbose_name='Convocatoria'),
        ),
    ]
