# Generated by Django 4.1.1 on 2022-10-12 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0004_torneo_logo_alter_torneo_invitacion_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegado_Inscripccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_delegado', models.CharField(max_length=50)),
                ('correo_delegado', models.CharField(max_length=30)),
                ('ci_delegado', models.CharField(max_length=15)),
                ('telefono_delegado', models.CharField(max_length=15)),
                ('recibo', models.ImageField(null=True, upload_to='static/imagenes/logos/', verbose_name='LogoTorneo')),
            ],
        ),
        migrations.CreateModel(
            name='Delegado_Pre_Inscripccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_delegado', models.CharField(max_length=50)),
                ('correo_delegado', models.CharField(max_length=30)),
                ('ci_delegado', models.CharField(max_length=15)),
                ('telefono_delegado', models.CharField(max_length=15)),
                ('recibo', models.ImageField(null=True, upload_to='static/imagenes/logos/', verbose_name='LogoTorneo')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('monto_inscripcion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_inscripcion', models.BooleanField(default=False)),
                ('id_torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.torneo')),
            ],
        ),
        migrations.CreateModel(
            name='Pre_Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('monto_inscripcion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_inscripcion', models.BooleanField(default=True)),
                ('id_torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.torneo')),
            ],
        ),
        migrations.DeleteModel(
            name='Etapa_Inscripcion',
        ),
        migrations.AddField(
            model_name='delegado_pre_inscripccion',
            name='id_pre_inscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.pre_inscripcion'),
        ),
        migrations.AddField(
            model_name='delegado_inscripccion',
            name='id_inscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.inscripcion'),
        ),
    ]
