# Generated by Django 4.1 on 2022-10-11 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0005_remove_etapa_inscripcion_tipo_inscripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegado_preinscripcion',
            name='correo_delegado_Preinscripcion',
            field=models.CharField(max_length=50),
        ),
    ]
