# Generated by Django 4.1 on 2022-10-18 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('torneo', '0005_delegado_inscripcion_delegado_preinscripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegado_inscripcion',
            name='id_delegadoIns',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delegado_preinscripcion',
            name='id_delegadoPreIns',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
