# Generated by Django 4.1 on 2022-10-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0006_alter_delegado_preinscripcion_correo_delegado_preinscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegado_inscripcion',
            name='correo_delegado_inscripcion',
            field=models.CharField(max_length=50),
        ),
    ]
