# Generated by Django 4.1 on 2022-10-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0007_delegado_entrenador_equipo_jugador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegado',
            name='nacimiento_delegado',
            field=models.DateField(null=True),
        ),
        
    ]
