# Generated by Django 4.1 on 2022-10-12 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0005_delegado_inscripccion_delegado_pre_inscripccion_and_more'),
        ('torneo', '0007_alter_delegado_inscripcion_correo_delegado_inscripcion'),
    ]

    operations = [
    ]
