# Generated by Django 4.1 on 2022-10-12 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0008_merge_20221012_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delegado_pre_inscripccion',
            name='id_pre_inscripcion',
        ),
        migrations.RemoveField(
            model_name='etapa_preinscripcion',
            name='id_torneo',
        ),
        migrations.RenameField(
            model_name='pre_inscripcion',
            old_name='estado_inscripcion',
            new_name='estado_Preinscripcion',
        ),
        migrations.RenameField(
            model_name='pre_inscripcion',
            old_name='fecha_fin',
            new_name='fecha_finPre',
        ),
        migrations.RenameField(
            model_name='pre_inscripcion',
            old_name='fecha_inicio',
            new_name='fecha_inicioPre',
        ),
        migrations.RenameField(
            model_name='pre_inscripcion',
            old_name='monto_inscripcion',
            new_name='monto_Preinscripcion',
        ),
        migrations.AlterField(
            model_name='delegado_inscripcion',
            name='id_etapa_inscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.inscripcion'),
        ),
        migrations.AlterField(
            model_name='delegado_preinscripcion',
            name='id_etapa_Preinscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.pre_inscripcion'),
        ),
        migrations.DeleteModel(
            name='Delegado_Inscripccion',
        ),
        migrations.DeleteModel(
            name='Delegado_Pre_Inscripccion',
        ),
        migrations.DeleteModel(
            name='Etapa_PreInscripcion',
        ),
    ]
