# Generated by Django 4.1 on 2022-10-21 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0008_alter_delegado_nacimiento_delegado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='id_delegado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='torneo.delegado'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='id_entrenador_equipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='torneo.entrenador'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='id_torneo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='torneo.torneo'),
        ),
        
    ]
