# Generated by Django 4.1 on 2022-10-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0009_alter_equipo_id_delegado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='apodo_jugador',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
