# Generated by Django 4.1 on 2022-10-30 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0010_jugador_apodo_jugador_delete_etapa_inscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenador',
            name='apodo_entrenador',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entrenador',
            name='nacionalidad_entrenador',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
