# Generated by Django 4.1 on 2022-11-03 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0011_entrenador_apodo_entrenador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='qr_inscripcion',
            field=models.ImageField(null=True, upload_to='static/imagenes/qrs/', verbose_name='qr2'),
        ),
        migrations.AddField(
            model_name='pre_inscripcion',
            name='qr_Preinscripcion',
            field=models.ImageField(null=True, upload_to='static/imagenes/qrs/', verbose_name='qr1'),
        ),
    ]
