# Generated by Django 4.1.1 on 2022-11-04 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0012_inscripcion_qr_inscripcion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Etapa_Inscripcion',
        ),
    ]
